on:
  push:
    branches:
      - main

env:
  HOST: https://digitalprojects.davidson.edu
  BASE_PATH: /scrollytellerdh

name: 🚀 Deploy Website
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: 🚧 Setup up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: 🛠 Install dependencies
        run: npm i
      - name: 🛠 Build project
        run: npm run build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.inkandbolts.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './build/'
          server-dir: './'
          dangerous-clean-slate: true
          protocol: ftps
      - name: 🖨 Print endpoint
        run: echo $HOST$BASE_PATH >> $GITHUB_STEP_SUMMARY
