on:
  push:
    branches:
      - main

env:
  HOST: https://digitallearning.davidson.edu
  BASE_PATH: /john-michael-murphy/scrollyteller

name: 🚀 Deploy Website
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: 🚧 Setup up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: 🛠 Install dependencies
        run: npm i
      - name: 🛠 Build project
        run: npm run build
      - name: 📂 Sync files
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ftp.inkandbolts.com
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: './build/'
      - name: 🖨 Print endpoint
        run: echo $HOST$BASE_PATH >> $GITHUB_STEP_SUMMARY
